default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
adapter : postgresql
database : railway
usename : postgres
password : kWAetPWrZwaL4tfGHz2M
host : containers-us-west-108.railway.app
port : 5793
pool : 5

